<a href="https://colab.research.google.com/github/HarshitaBhatia27/Deep-Learning-/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch is an open source ML framework used for developing and training DL models.While Tensorflow focuses more on static computation graphs, pytorch emphasizes dynamic computation graphs.

In [1]:
import torch

Tensors

--> pytorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-D array

In [2]:
t1= torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2= torch.tensor([1.,2.,3.,4.]) #vector
t2

tensor([1., 2., 3., 4.])

In [6]:
t3= torch.tensor([[5.,6.],[7,8],[9,10]]) #matrix
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
t3.dtype

torch.float32

In [17]:
t4= torch.tensor([[[11,12,13],[13,14,15]],[[15,16,17],[17,18,20]]])  #3-D array
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 20]]])

Tensors can have any no. of dimensions and diff lengths along each dimension. We can inspect the length along each dimension using .shape property

In [11]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [12]:
print(t2)
t2.shape
#shape is the no. of elements

tensor([1., 2., 3., 4.])


torch.Size([4])

In [13]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [18]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 20]]])


torch.Size([2, 2, 3])

In [19]:
#matrix

t5 = torch.tensor([[5.,6.,7.],[7,8],[9,10]])

ValueError: ignored

Note: It is not possible to create tensors with an improper shape in pytorch.

# Tensor operations and gradients

In [20]:
x=torch.tensor(3.)
w= torch.tensor(4., requires_grad=True)
b=torch.tensor(5.,requires_grad=True) #requires_grad is True meaning that at time of back propagation their gradient will be calculated
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [21]:
y= w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [23]:
y.backward() #compute derivates

In [25]:
w.grad

tensor(3.)

In [24]:
#display gradient
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


For x, the gradient was not true so it showed none but for other 2 the gradients are calculated.

**Tensor Functions**

In [26]:
t6= torch.full((3,2),42) #create tensor with a fixed value for every element
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [27]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [28]:
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [32]:
#concat tensors with compatible shape
t7= torch.cat((t3,t6),axis=0)  #axis=1 is col wise, 0 is row wise
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [34]:
t8=torch.sin(t7) #sin of each element
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [38]:
t9=t8.reshape(3,2,2) #3-D
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

Interoperability with Numpy

In [39]:
import numpy as np
x= np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [40]:
y= torch.from_numpy(x) #convert numpy array to tensor
y

tensor([[1, 2],
        [3, 4]])

In [41]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [44]:
#tensor to numpy array is converted using .numpy method
z=y.numpy()
z

array([[1, 2],
       [3, 4]])

Linear-regression using pytorch

In [46]:
#making train data
#(temp,rainfall,humidity)
inputs= np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]],dtype='float32')

In [47]:
#targets (apples,oranges)
target=np.array([[56,70],[81,101],[119,133],[22,37],[103,119]],dtype='float32')

In [48]:
#convert input and target to tensor
inputs=torch.from_numpy(inputs)
target=torch.from_numpy(target)
print(inputs,"\n")
print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) 

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [49]:
#weights and biases
w= torch.randn(2,3,requires_grad=True)
b= torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.6510,  0.1770,  1.8137],
        [ 1.4961,  0.9741,  0.2911]], requires_grad=True)
tensor([ 1.5542, -1.1863], requires_grad=True)


In [51]:
#model
def model(x):
  return x @ w.t()+b

# x is multiplied with transpose of w

In [55]:
#PREDICTTED
preds= model(inputs)
print(preds)

tensor([[ 43.8809, 185.8123],
        [ 73.9683, 239.3115],
        [ 73.8336, 276.3887],
        [  9.8701, 204.0754],
        [100.5894, 215.9359]], grad_fn=<AddBackward0>)


In [54]:
#actual
print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [57]:
#loss function mse
def MSE(actual,target):
  diff= actual-target
  return torch.sum(diff * diff)/diff.numel()

#This finalizes the calculation of the mean squared error (MSE) by dividing the sum of squared differences by the total number of elements.
#This yields the average squared difference between corresponding elements in the tensors, which is a measure of how much the tensors differ on average.

In [58]:
#error
loss=MSE(target,preds)
print(loss)

tensor(9280.2939, grad_fn=<DivBackward0>)


In [59]:
loss.backward()

print(w.grad,"\n")
print(b.grad)

tensor([[-1371.5281, -1647.2146,  -841.6702],
        [11449.1484, 11127.0049,  7023.1431]]) 

tensor([-15.7715, 132.3048])


In [60]:
#adjust weight and reset grad
with torch.no_grad():
  w -= w.grad* 1e-5  #1e-5 taken as learning rate
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [61]:
print(w)
print(b)

tensor([[-0.6373,  0.1935,  1.8221],
        [ 1.3816,  0.8628,  0.2209]], requires_grad=True)
tensor([ 1.5544, -1.1876], requires_grad=True)


In [62]:
preds=model(inputs)
print(preds)

tensor([[ 46.3478, 166.9781],
        [ 77.2048, 214.6049],
        [ 77.7224, 247.4430],
        [ 12.2889, 185.0128],
        [103.7064, 192.4365]], grad_fn=<AddBackward0>)


In [63]:
loss=MSE(target,preds)
print(loss)

tensor(6461.4951, grad_fn=<DivBackward0>)


In [65]:
#trainig for multiple epochs
for i in range(400):
  preds= model(inputs)
  loss=MSE(target,preds)
  loss.backward()

  with torch.no_grad():
    w -= w.grad* 1e-5  #1e-5 taken as learning rate
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()
  print(f"Epochs({i}/{400}) & Loss {loss}")

Epochs(0/400) & Loss 65.5509262084961
Epochs(1/400) & Loss 65.39494323730469
Epochs(2/400) & Loss 65.2396240234375
Epochs(3/400) & Loss 65.08502960205078
Epochs(4/400) & Loss 64.93115234375
Epochs(5/400) & Loss 64.77799987792969
Epochs(6/400) & Loss 64.6255874633789
Epochs(7/400) & Loss 64.47380065917969
Epochs(8/400) & Loss 64.32274627685547
Epochs(9/400) & Loss 64.17237091064453
Epochs(10/400) & Loss 64.02271270751953
Epochs(11/400) & Loss 63.873626708984375
Epochs(12/400) & Loss 63.72522735595703
Epochs(13/400) & Loss 63.577545166015625
Epochs(14/400) & Loss 63.430519104003906
Epochs(15/400) & Loss 63.284034729003906
Epochs(16/400) & Loss 63.138282775878906
Epochs(17/400) & Loss 62.99311065673828
Epochs(18/400) & Loss 62.84864044189453
Epochs(19/400) & Loss 62.7047233581543
Epochs(20/400) & Loss 62.56147003173828
Epochs(21/400) & Loss 62.41878128051758
Epochs(22/400) & Loss 62.276756286621094
Epochs(23/400) & Loss 62.13530349731445
Epochs(24/400) & Loss 61.994407653808594
Epochs(25/

In [66]:
preds=model(inputs)
Loss = MSE(target,preds)
print(Loss)

tensor(29.8245, grad_fn=<DivBackward0>)


In [67]:
from math import sqrt
sqrt(Loss)

5.461177269470302

In [68]:
preds

tensor([[ 56.9236,  70.5641],
        [ 86.3279,  97.5390],
        [109.7139, 139.6660],
        [ 18.6017,  39.3299],
        [110.8424, 112.1036]], grad_fn=<AddBackward0>)

In [69]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])