<a href="https://colab.research.google.com/github/HarshitaBhatia27/Deep-Learning-/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

print("Tensorflow version: {}".format(tf.__version__))
print("Eager execution is : {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))



Tensorflow version: 2.12.0
Eager execution is : True
Keras version: 2.12.0


GPU/CPU check

In [ ]:
if tf.test.is_gpu_available():
  print('Running on GPU')
else:
  print("Running on CPU")


Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


Running on GPU


In [ ]:
tf.config.list_physical_devices('CPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

Tensor Constant

In [ ]:
Tens=tf.constant(42)
Tens

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [ ]:
Tens.numpy()  #get the value

42

In [ ]:
Tens1=tf.constant(1,dtype=tf.int64)
Tens1 #value 1 and datatype is int64

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
Tens_x=tf.constant([[4,2],[9,5]])
print(Tens_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [ ]:
Tens_x.numpy()

array([[4, 2],
       [9, 5]], dtype=int32)

In [ ]:
print("Shape", Tens_x.shape)
print(Tens_x.dtype)

Shape (2, 2)
<dtype: 'int32'>


Commonly used methods is to generate constant tf.ones and tf.zeros like of numpy np.ones and np.zeros

In [ ]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [ ]:
print(tf.zeros(shape=(3,3)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [ ]:
const2=tf.constant([[3,4,5],[3,4,5]])
const3=tf.constant([[1,2,3],[1,2,3]])
result=tf.add(const2,const3)
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


Random constant


In [ ]:
#normal dist random const
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.713091  ,  0.07995564],
       [ 0.8125579 , -0.75063556]], dtype=float32)>

In [ ]:
tf.random.uniform(shape=(2,2),minval=0,maxval=5,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [1, 3]], dtype=int32)>

Variables ---> special tensor that is used to store variables and needs to be initialized with some values

In [ ]:
var0= 23 #python variable
var1= tf.Variable(24) #rank 0 tensor
var2=tf.Variable([[[0.,1.,2.],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]]) #rank 3 tensor
var0, var1, var2

(23,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=24>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

The default dtype for int is int32 and float is fload32

In [ ]:
#changing dtype explicitly
float_var64=tf.Variable(100,dtype=tf.float16)
float_var64

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=100.0>

To reassign a variable, use var.assign()

In [ ]:
var_reassign = tf.Variable(89.0)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [ ]:
var_reassign.assign(100.)
var_reassign
#value if changed

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=100.0>

In [ ]:
initial_value=tf.random.normal(shape=(2,2))
a=tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.0843743 ,  0.59113544],
       [-1.2657121 ,  0.9939107 ]], dtype=float32)>


In [ ]:
new_value= tf.random.normal(shape=(2,2))
a.assign(new_value)
for i in range(2):
  for j in range(2):
    assert a[i,j]==new_value[i,j]

In [ ]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
  for j in range(2):
    assert a[i,j]==new_value[i,j]+added_value[i,j]

We can assign "=" with assign(value), or assign_add(value) with "+=" or assign_sub(value) with "-="

Shaping a tensor

In [ ]:
tensor=tf.Variable([[[0.,1.,2.],[3.,4.,5]],[[6.,7.,8.],[9.,10.,11.]]]) #tensor variable
print(tensor.shape)

(2, 2, 3)


In [ ]:
tensor1= tf.reshape(tensor,[2,6]) # 2 rows 6 cols
tensor2=tf.reshape(tensor,[1,12]) # 1 row 12 cols
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [ ]:
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

**Ranking(dimensions) of a tensor**


The rank of a tensor is the no. of dimensions it has, that is, the no. of indices that are required to specify any particular element of that tensor.

In [ ]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [ ]:
tf.rank(tensor)
# 3 dimensions so rank is 3
#the shape is () because the o/p here is a scalar value

<tf.Tensor: shape=(), dtype=int32, numpy=3>

Specifying an element of a tensor

In [ ]:
tensor3= tensor[1,0,2] #slice 1, row 0, col 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

Casting a tensor to a Numpy/Python variable

In [ ]:
print(tensor.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [ ]:
print(tensor[0,0,2].numpy())
#first array(0th index), first row(0th index), 3rd element(2nd index)

2.0


Finding the size (no. of elements) of a tensor

In [ ]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [ ]:
tensor3.dtype #dtype of tensor

tf.float32

## Tensorflow Mathematical Operations

Can be used as numpy for artifical operations. Tensorflow can not execute these operations on the GPU or TPU

In [ ]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))
c=a+b
d= tf.square(c)
e= tf.exp(c)
print("A: ", a)
print("B: " ,b)
print("C: ",c)
print("D: ", d)
print("E: ", e)

A:  tf.Tensor(
[[-0.33164555 -0.08448225]
 [-0.9384639   1.514233  ]], shape=(2, 2), dtype=float32)
B:  tf.Tensor(
[[-0.21453856 -1.7643473 ]
 [ 0.49738353  0.8297921 ]], shape=(2, 2), dtype=float32)
C:  tf.Tensor(
[[-0.5461841 -1.8488295]
 [-0.4410804  2.3440251]], shape=(2, 2), dtype=float32)
D:  tf.Tensor(
[[0.2983171  3.4181705 ]
 [0.19455191 5.494454  ]], shape=(2, 2), dtype=float32)
E:  tf.Tensor(
[[ 0.57915556  0.15742132]
 [ 0.643341   10.423106  ]], shape=(2, 2), dtype=float32)


Performing element-wise primitive tensor operations

In [ ]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

In [ ]:
tensor-tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

**Broadcasting**

--> Element-wise tensor operations support broadcasting in the same way that numpy arrays do.

---> The simplest eg is that of multiplying a tensor by a scalar

In [ ]:
tensor4=tensor*4
tensor4

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  4.,  8.],
        [12., 16., 20.]],

       [[24., 28., 32.],
        [36., 40., 44.]]], dtype=float32)>

Transpose Matrix Multiplication

In [ ]:
matrix_u = tf.constant([[3,4,3]])
matrix_v = tf.constant([[1,2,1]])
tf.matmul(matrix_u, tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

In [ ]:
matrix_u

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[3, 4, 3]], dtype=int32)>

In [ ]:
matrix_v

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 1]], dtype=int32)>

Casting a tensor to another(tensor) datatype

In [ ]:
i = tf.cast(tensor1, dtype=tf.int32)
i

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]], dtype=int32)>

In [ ]:
tensor2 = tf.reshape(tensor,[1,12])
tensor2 =tf.cast(tensor2,dtype=tf.int32)
tensor2

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]], dtype=int32)>

In [ ]:
#with truncation
j= tf.cast(tf.constant(4.9),dtype=tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

Declaring ragged tensors

---> a ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths. There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged array.

---> Unlike regular tensors, where all dimensions have fixed sizes, ragged tensors allow inner dimensions to have different lengths, essentially accommodating irregular or varying lengths within the same tensor.

In [ ]:
ragged= tf.ragged.constant([[5,2,6,1],[],[4,10,7],[8],[6,7]])

print(ragged)
print(ragged[0,:]) #first element array
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


Filling the sqaured diff b/w two tensors

In [ ]:
varx=[1,3,5,7,11]
vary=5
varz=tf.math.squared_difference(varx,vary)
varz.numpy()

# (1-5)^2, (3-5)^2...

array([16,  4,  0,  4, 36], dtype=int32)

Finding mean


---> tf.reduce_mean(input_tensor, axis=None, keepdims=None,name=None)

In [ ]:
numbers= tf.constant([[4.,5.],[7.,3.]])

In [ ]:
#find mean across all axes
tf.reduce_mean(input_tensor=numbers)

# (4.+ 5.+ 7. + 3.)/4 = 4.75

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

In [ ]:
#find mean across all cols (axis=0)
tf.reduce_mean(input_tensor=numbers, axis=0)

#[ (4. + 5.)/2 , (7.+ 3.)/2 ]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

In [ ]:
# rows

tf.reduce_mean(input_tensor=numbers, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

In [ ]:
#when keepdims is true, the reduced axis is retained with a length of 1

tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True) #original jo shape hai vhi rhegi

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

**Generating tensors filled with random values**\




*   using tf.random.normal(shape,mean=0,dtype=tf.float32,seed=None,name=None)  ---> normal dist.

*   tf.random.uniform(shape, minval=0,maxval=None,dtype=tf.fload32, seed=None, name=None) ---> uniform dist.



In [ ]:
ran = tf.random.normal(shape=(3,2),mean=10.0,stddev=2.0)
print(ran)

tf.Tensor(
[[ 9.022332  11.82684  ]
 [ 6.536682   9.0460205]
 [ 8.5479765  9.89463  ]], shape=(3, 2), dtype=float32)


In [ ]:
tf.random.uniform(shape=(2,4), minval=0,maxval=None,dtype=tf.float32, seed=None, name=None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.00302923, 0.272341  , 0.97259986, 0.84306777],
       [0.03220475, 0.22341323, 0.5906687 , 0.21297681]], dtype=float32)>

Setting the seed

In [ ]:
tf.random.set_seed(11)
ran1= tf.random.uniform(shape= (2,2),maxval=10,dtype=tf.int32)
ran2 = tf.random.uniform(shape = (2,2),maxval=10,dtype=tf.int32)
print(ran1) #first call
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [ ]:
tf.random.set_seed(11)
ran1= tf.random.uniform(shape= (2,2),maxval=10,dtype=tf.int32)
ran2 = tf.random.uniform(shape = (2,2),maxval=10,dtype=tf.int32)
print(ran1) #second call
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


The values are same because the seed has been set

Example of random values using dices

In [ ]:
dice1 = tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
dice_sum = dice1 + dice2

resulting_matrix= tf.concat(values=[dice1,dice2,dice_sum],axis=1)
print(resulting_matrix)

tf.Tensor(
[[ 5  5 10]
 [ 4  3  7]
 [ 5  3  8]
 [ 3  3  6]
 [ 1  4  5]
 [ 4  1  5]
 [ 5  1  6]
 [ 6  4 10]
 [ 3  3  6]
 [ 2  3  5]], shape=(10, 3), dtype=int32)


Find indices of a largest and smallest element

In [ ]:
t5 = tf.constant([2,11,5,42,7,19,-6,-11,29])
print(t5)

i = tf.argmax(input=t5)
print('index of max: ', i)
print("max element: ", t5[i].numpy())

i = tf.argmin(input=t5,axis=0).numpy()
print('index of min: ', i)
print("min element: ", t5[i].numpy())

t6= tf.reshape(t5, [3,3])
print(t6)

i=tf.argmax(input=t6,axis=0).numpy()
print("indices of max down rows: ", i)

i=tf.argmin(input=t6,axis=0).numpy()
print("indices of min down rows: ", i)

tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)
index of max:  tf.Tensor(3, shape=(), dtype=int64)
max element:  42
index of min:  7
min element:  -11
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max down rows:  [1 0 2]
indices of min down rows:  [2 2 0]


In [ ]:
i=tf.argmax(input=t6,axis=1).numpy()
print("indices of max down cols: ", i)

i=tf.argmin(input=t6,axis=1).numpy()
print("indices of min down cols: ", i)

indices of max down cols:  [1 0 2]
indices of min down cols:  [0 1 1]


Saving and restoring tensor values using a checkpoint

In [ ]:
variable = tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint = tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('./vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
variable
checkpoint.restore(save_path)
print(variable)


<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]], dtype=int32)>


Using tf.function

--> It will take a python func and return a tensorflow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the python func.

In [ ]:
def f1(x,y):
  return tf.reduce_mean(input_tensor=tf.multiply(x ** 2, 5) + y**2)

f2 = tf.function(f1) #convert in tensorflow graph
x=tf.constant([4., -5.])
y= tf.constant([2.,3.])

assert f1(x,y).numpy()== f2(x,y).numpy()


Calculate gradient ----> gradient tape

--> it can automatically track the gradient of any variable.

--> enables automatic differentiation and gradient computation for training neural networks through backpropagation

In [ ]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
  tape.watch(a)
  c=tf.sqrt(tf.square(a)+tf.square(b))
  dc_da=tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446555 -0.7976701 ]], shape=(2, 2), dtype=float32)


In [ ]:
# if we have a variable, we dont need to use tape.watch
a=tf.Variable(a)
with tf.GradientTape() as Tape:
  c=tf.sqrt(tf.square(a)+ tf.square(b))
  dc_da= Tape.gradient(c,a) #differentiate wrt a
  print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446555 -0.7976701 ]], shape=(2, 2), dtype=float32)


In [ ]:
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as Tape:
    c=tf.sqrt(tf.square(a)+ tf.square(b))
    dc_da= Tape.gradient(c,a) #differentiate wrt a
  d2c_d2a=outer_tape.gradient(dc_da,a) #double derivative
  print(d2c_d2a)

tf.Tensor(
[[0.4264985  0.6867533 ]
 [0.44663432 0.50159544]], shape=(2, 2), dtype=float32)
