In [1]:
import numpy as np
import pandas as pd
import joblib
import matplotlib.pyplot as plt

In [11]:
class Perceptron:
    def __init__(self,eta,epochs):
        self.weights=np.random.randn(3)* 1e-4
        print(f"self.weights: {self.weights}")
        self.eta=eta
        self.epochs=epochs
    def activationFunction(self,inputs,weights):
        z=np.dot(inputs,weights)
        return np.where(z>0,1,0)
  

    def fit(self,X,y):
        self.X=X
        self.y=y
        
        X_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]
        print(f"X_with_bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print(f"for epoch: {epoch}")
            y_hat=self.activationFunction(X_with_bias,self.weights)
            print(f"predicted values: \n{y_hat}")
            error=self.y-y_hat
            print(f"error: \n{error}")
            self.weights=self.weights + self.eta * np.dot(X_with_bias.T, error)
            print(f"updated weights: \n{self.weights}")
            
    def predict(self,X):
        X_with_bias=np.c_[X,-np.ones((len(self.X),1))]
        return self.activationFunction(X_with_bias,self.weights)

### AND OPERATION

In [12]:
data={'x1':[0,0,1,1],'x2':[0,1,0,1],'y':[0,0,0,1]}

AND=pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [13]:
X=AND.drop('y',axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [14]:
y=AND['y']
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [15]:
model=Perceptron(eta=0.5,epochs=10)
model.fit(X,y)

self.weights: [5.29840664e-06 9.78636796e-05 1.16353642e-04]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted values: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[ 0.5000053   0.50009786 -0.49988365]
for epoch: 1
predicted values: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
[5.29840664e-06 9.78636796e-05 1.00011635e+00]
for epoch: 2
predicted values: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[0.5000053  0.50009786 0.50011635]
for epoch: 3
predicted values: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.5000053  0.50009786 0.50011635]
for epoch: 4
predicted values: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.5000053  0.50009786 0.50011635]
for epoch: 5
predicted values: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: 

In [16]:
model.predict(X)

array([0, 0, 0, 1])

In [17]:
model.weights

array([0.5000053 , 0.50009786, 0.50011635])

### OR Operation 

In [18]:
data={'x1':[0,0,1,1],'x2':[0,1,0,1],'y':[0,1,1,1]}

OR=pd.DataFrame(data)
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [19]:
X=OR.drop('y',axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [21]:
y=OR['y']
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [22]:
model=Perceptron(eta=0.5,epochs=10)
model.fit(X,y)

self.weights: [-9.17502824e-06  9.04508649e-05 -4.19118710e-05]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted values: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[-9.17502824e-06  9.04508649e-05  4.99958088e-01]
for epoch: 1
predicted values: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights: 
[ 0.99999082  1.00009045 -1.00004191]
for epoch: 2
predicted values: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[ 0.99999082  1.00009045 -0.50004191]
for epoch: 3
predicted values: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[ 9.99990825e-01  1.00009045e+00 -4.19118710e-05]
for epoch: 4
predicted values: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.99999082 1.00009045 0.49995809]
for epoch: 5
predicted values: 
[0 1 1 1]
error: 
0    0
1  

In [23]:
model.predict(X)

array([0, 1, 1, 1])

In [24]:
model.weights

array([0.99999082, 1.00009045, 0.49995809])

### XOR Operation

In [25]:
data={'x1':[0,0,1,1],'x2':[0,1,0,1],'y':[0,1,1,0]}

XOR=pd.DataFrame(data)
XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [26]:
X=XOR.drop('y',axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [27]:
y=XOR['y']
y

0    0
1    1
2    1
3    0
Name: y, dtype: int64

In [29]:
model=Perceptron(eta=0.5,epochs=100)
model.fit(X,y)

self.weights: [-1.44372667e-05 -7.52151473e-05  1.15010676e-04]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted values: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 0.49998556  0.49992478 -0.99988499]
for epoch: 1
predicted values: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-1.44372667e-05 -7.52151473e-05  1.15010676e-04]
for epoch: 2
predicted values: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 0.49998556  0.49992478 -0.99988499]
for epoch: 3
predicted values: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-1.44372667e-05 -7.52151473e-05  1.15010676e-04]
for epoch: 4
predicted values: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 0.49998556  0.49992478 -0.99988499]
for epoch: 5
predicted values: 
[1 1 1 1]
error: 
0   -1


Name: y, dtype: int64
updated weights: 
[ 0.49998556  0.49992478 -0.99988499]
for epoch: 81
predicted values: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-1.44372667e-05 -7.52151473e-05  1.15010676e-04]
for epoch: 82
predicted values: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 0.49998556  0.49992478 -0.99988499]
for epoch: 83
predicted values: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-1.44372667e-05 -7.52151473e-05  1.15010676e-04]
for epoch: 84
predicted values: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 0.49998556  0.49992478 -0.99988499]
for epoch: 85
predicted values: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-1.44372667e-05 -7.52151473e-05  1.15010676e-04]
for epoch: 86
predicted values: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64


In [30]:
model.predict(X)

array([0, 0, 0, 0])

Our model is not able to predict XOR gate. So it is not able to solve this complex problem.